ALTER TABLE signals ADD COLUMN IF NOT EXISTS tp3_price NUMERIC;
ALTER TABLE signal_evidence ADD COLUMN IF NOT EXISTS passed BOOLEAN;
ALTER TABLE signals ADD COLUMN IF NOT EXISTS ai_decision VARCHAR(50);
ALTER TABLE signals ADD COLUMN IF NOT EXISTS ai_reasoning TEXT;
ALTER TABLE strategy_states ADD COLUMN IF NOT EXISTS symbol VARCHAR(20);
ALTER TABLE strategy_states ADD COLUMN IF NOT EXISTS timeframe VARCHAR(10);
NOTIFY pgrst, 'reload schema';
