[phases.setup]
nixPkgs = ["nodejs_20", "python311", "gcc"]

[phases.install]
cmds = [
    "npm ci",
    "pip3 install -r python-engine/requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
